# Generated by Django 2.1 on 2018-08-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_closed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.PaymentType'),
        ),
    ]
